-- AlterTable
ALTER TABLE `TransactionIn` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `TransactionOut` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `exitDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
